### ISSUE TITLE
Mysql/Maria DB does not support migration DDL in transaction

### ISSUE THREAD

**Issue by pk16011990** [shopsys/migrations#6]
Hello,

running migrations in transaction - It sounds as very good improvement instead of basic Doctrine migrations, but ... In Mysql DDL (create, alter, drop) commands are out of transaction and on rollback these changes are persist, but migraton looks like rollbacked.

In my opinion it does not have a solution, It is a feature that should be documented or It shoud be allowed on this engines.

**Comment by simara-svatopluk** [comment]
transfered to monorepo https://github.com/shopsys/shopsys/issues/65
